#!/bin/bash

lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php

#permissions
chown -R www-data:www-data /srv/rpirrigate
chmod -R 775 /srv/rpirrigate

#create log files and give permissions

mkdir -p /var/log/rpirrigate
touch /var/log/rpirrigate/status.log
touch /var/log/rpirrigate/error.log
chown -R www-data:www-data /var/log/rpirrigate
chmod -R 775 /var/log/rpirrigate

chmod 755 /etc/logrotate.d/rpirrigate
chown root:root /etc/logrotate.d/rpirrigate

chmod 755 /etc/init.d/rpirrigate
chown root:root /etc/init.d/rpirrigate

# change directory and port of lighttpd
sed 's/server.document-root        = "\/var\/www\/html"/server.document-root        = "\/srv\/rpirrigate\/web"/' /etc/lighttpd/lighttpd.conf > /etc/lighttpd/lighttpd.conf
sed 's/server.port                 = 80/server.port                 = 667/' /etc/lighttpd/lighttpd.conf > /etc/lighttpd/lighttpd.conf


insserv rpirrigate

#Start services

service rpirrigate start
service lighttpd restart